Add the assassin character to the bmr edition
nyuszika7h/Blood-on-the-Clocktower-Storyteller-Discord-Bot pull request #5
Opened 2021-02-26 19:16 UTC by abitofevrything

Added the full assassin character to the bmr edition.

I've tested it in the following situations :
- Ending game night 2 due to killing imp
- Killing yourself night 2
- Killing townsfolk night 2
- Killing minion night 2
- Ending game night 3 due to killing imp

2021-02-26 19:33 UTC, nyuszika7h requested changes

2021-02-26 19:33 UTC, nyuszika7h commented on botc/abilities.py
> +    - l earn: ravenkeeper
```suggestion
    - learn: ravenkeeper
```

2021-02-26 19:33 UTC, nyuszika7h commented on botc/abilities.py
> +    - assasinate: assassin
```suggestion
    - assassinate: assassin
```

2021-03-19 12:21 UTC, abitofevrything commented
Will create new PR with conflicts resolved once BMR is done

2021-03-19 12:21 UTC, closed without merging